name: Build and Publish Artifacts

on:
  push:
    branches: [ main ]  # oder dein Branchname
  workflow_dispatch:    # erlaubt manuelles Ausführen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'  # oder deine Version

    - name: Restore dependencies
      run: dotnet restore ./src/ShadowKit.sln 

    - name: Build
      run: dotnet build ./src/ShadowKit.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./src/ShadowKit.sln --configuration Release --no-build

    - name: Pack IO
      run: dotnet pack ./src/ShadowKit.IO/ShadowKit.IO.csproj -o ./publish --no-restore

    - name: Pack Text
      run: dotnet pack ./src/ShadowKit.Text/ShadowKit.Text.csproj -o ./publish --no-restore

    - name: Pack Threading
      run: dotnet pack ./src/ShadowKit.Threading/ShadowKit.Threading.csproj -o ./publish --no-restore

    - name: Pack MetaPackage
      run: dotnet pack ./src/ShadowKit/ShadowKit.csproj -o ./publish --no-restore

    # - name: Push to NuGet
    #   run: dotnet nuget push ./publish/*.nupkg --api-key ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ShadowWriter-${{ github.run_number }}
        path: ./publish
